### ISSUE TITLE
make CSS indents consistent

### ISSUE THREAD

**Issue by greglinch** [lexinal/gallery-spring#3]
Such as here: https://github.com/lexinal/gallery-spring/blob/master/gallery.css#L37

In general, I'd recommend using 4 spaces (or setting tabs to equal 4 spaces in Sublime) to improve readability.

**Comment by lexinal** [comment]
![indent](https://user-images.githubusercontent.com/46660807/53534384-a5264980-3acc-11e9-9b22-ca0a466d1491.PNG)
It shows that it was indented. So strange! :/
